### Importar librerias:
 - pip install "libreria" para instalar en el ordenador.
 - import "librería" as "abreviación deseada" para trabajar con ella.

In [13]:
import numpy  as np
import pandas as pd

# Variables
- En python no hay comandos para declarar variables, simplemente asigno el nombre a un valor.
- Podemos cambiar el tipo de una variable despues de haberla declarado.
- Python ahce diferenciación entre mayusculas y minúscolas

In [14]:
variable_entera = 25
print("Inicialmente la  variable tiene el valor de:",variable_entera) #Para concatenar variables numericas uso ","
variable_entera = "casa"
print("Ahora la  variable tiene el valor de:"+variable_entera) #Para concatenar variables de texto uso ","

A = 5
a = 65

print("La variable A es:",A,"Y la a es:",a)

Inicialmente la  variable tiene el valor de: 25
Ahora la  variable tiene el valor de:casa
La variable A es: 5 Y la a es: 65


---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
Podemos fijar el tipo de una variable haciendo un casting como en la siguiente celda

In [15]:
x = str(3)    # x  es una cadena de valor '3'
y = int(3)    # y  es un entero de valor   3
z = float(3)  # z es un float de valor     3.0
print(x,y,z)

3 3 3.0


---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
Podemos obtener el tipo de variable con la función "type()"

In [16]:
dato_x = type(x)
dato_y = type(y)
dato_z = type(z)
print("El tipo de dato de x es",dato_x, "el de y:",dato_y, "y el de z",dato_z)

El tipo de dato de x es <class 'str'> el de y: <class 'int'> y el de z <class 'float'>


### Formas de llamado a variables

In [17]:
#Camel Case - Cada palabra menos la primera empieza por mayúscula:

myVariableName = "John"

#Pascal Case - Cada palabra empieza por mayúscula:

MyVariableName = "John"

#Snake Case - Cada palabra está separada por una barra baja:

my_variable_name = "John"

# Arrays
- Podemos declarar arrays de una forma muy similar a la de matlab.
- Para iterar sobre una lista y cambiar valores en concreto, debo usar la celda inferior.

    ### Range():
    Es el equivalente a decir los valores de uno en uno desde en el intervalo [0,input-1]. Es por esto que nos permite recorres todos los elementos. 
    ### Len():
    Devuelve el número de elementos de un array.
https://www.w3schools.com/python/python_variables_multiple.asp

In [18]:
Mi_Array = [1, 5 ,8 ,9, 4, 5 ,7 ,8 ,9, 20, 24 ]

for indice in range(len(Mi_Array)):
    if Mi_Array[indice] >= 8:
        Mi_Array[indice] = 10
        
print(Mi_Array)

[1, 5, 10, 10, 4, 5, 7, 10, 10, 10, 10]


In [19]:
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)
# Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


# Sentencias if

In [20]:
Aitor = 20
Diego = 22

if Aitor > Diego:
    print("Aitor tiene más edad que Diego")
else:
    print("Diego tiene más edad que Aitor")

Diego tiene más edad que Aitor


### Manipulacion de archivos

In [21]:
file = open("Añadir extensiones.txt","r")

archivo_texto = pd.read_csv("Añadir extensiones.txt")

archivo_texto

En ruta deseada usar este orden de comandos   o los dos juntos con &&:
0  1) pip install jupyter_contrib_nbextensions                        NaN
1       2) jupyter contrib nbextension install                        NaN

  #### Creación de archivos
  
- "x": Crea un archivo, pero devuelve un error si ya existe.
- "a": Crea un archivo en caso de que no exista y escribe al final del documento.
- "w": Crea un archivo y escribe en caso de que no exista y sobreescribe el archivo.

In [22]:
File = open("archivo_vacio.txt", "a")

File.write("Now the file has more content!")
File.close()