### Importar librerias:
 - !pip install "libreria"

In [2]:
import numpy as np


In [3]:
Aitor = 20
Diego = 22

if Aitor > Diego:
    print("Aitor tiene más edad que Diego")
else:
    print("Diego tiene más edad que Aitor")

Diego tiene más edad que Aitor


In [4]:
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)
# Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
# Array de tres dimensiones
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
