### Importar librerias:
 - !pip install "libreria"

In [6]:
import numpy as np


In [7]:
Aitor = 20
Diego = 22

if Aitor > Diego:
    print("Aitor tiene más edad que Diego")
else:
    print("Diego tiene más edad que Aitor")

Diego tiene más edad que Aitor


In [8]:
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)
# Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [9]:
if Aitor> Diego:
    print("Esto es un if")
else:
    print("Esto es un if 2")

Esto es un if 2
